package storage.model;
// Generated Jul 25, 2025, 4:22:25 PM by Hibernate Tools 5.6.15.Final

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice implements java.io.Serializable {

	private Integer id;
	private ProductInfo productInfo;
	private User user;
	private String code;
	private int type;
	private int qty;
	private BigDecimal price;
	private int activeFlag;
	private Date createDate;
	private Date updateDate;
    private Timestamp fromDate;
    
    private Timestamp toDate;
    
    private Integer productId;

	public Invoice() {
	}

	public Invoice(ProductInfo productInfo, String code, int type, int qty, BigDecimal price, int activeFlag,
			Date createDate, Date updateDate) {
		this.productInfo = productInfo;
		this.code = code;
		this.type = type;
		this.qty = qty;
		this.price = price;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Invoice(ProductInfo productInfo, User user, String code, int type, int qty, BigDecimal price, int activeFlag,
			Date createDate, Date updateDate) {
		this.productInfo = productInfo;
		this.user = user;
		this.code = code;
		this.type = type;
		this.qty = qty;
		this.price = price;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Timestamp getFromDate() {
		return fromDate;
	}

	public void setFromDate(Timestamp fromDate) {
		this.fromDate = fromDate;
	}

	public Timestamp getToDate() {
		return toDate;
	}

	public void setToDate(Timestamp toDate) {
		this.toDate = toDate;
	}

	public Integer getProductId() {
		return productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public ProductInfo getProductInfo() {
		return this.productInfo;
	}

	public void setProductInfo(ProductInfo productInfo) {
		this.productInfo = productInfo;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
